---
permalink: deploy/reference_port_requirements_for_vsc.html 
sidebar: sidebar 
keywords: port requirements 
summary: Por padrão, as ferramentas do ONTAP usam portas designadas para permitir a comunicação entre seus componentes, que incluem sistemas de storage e o VMware vCenter Server. Se você tiver firewalls ativados, você deve garantir que os firewalls estejam definidos para permitir exceções. 
---
= Requisitos de porta para ferramentas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Por padrão, as ferramentas do ONTAP usam portas designadas para permitir a comunicação entre seus componentes, que incluem sistemas de storage e o VMware vCenter Server. Se você tiver firewalls ativados, você deve garantir que os firewalls estejam definidos para permitir exceções.

Para firewalls que não sejam Windows, você deve conceder manualmente acesso a portas específicas que as ferramentas do ONTAP usam. Se você não conceder acesso a essas portas, uma mensagem de erro como a seguinte será exibida.

`Unable to communicate with the server.`

As ferramentas do ONTAP usam as seguintes portas TCP bidirecionais padrão:

|===


| *Número da porta padrão* | *Descrição* 


 a| 
9083
 a| 
Quando ativado, o provedor VASA e o adaptador de replicação de armazenamento (SRA) usam essa porta para se comunicar com o vCenter Server. Essa porta também é necessária para obter as configurações TCP/IP. Essa porta precisa ser habilitada no firewall desde os hosts ESXi até as ferramentas do ONTAP para o dispositivo VMware vSphere. Essa porta é usada para baixar o pacote de suporte VP, acessar a interface de usuário da Web-CLI e controlar a comunicação de caminho do VMware para o VP.



 a| 
443
 a| 
Dependendo de como você configurou suas credenciais, o VMware vCenter Server e os sistemas de armazenamento escutam comunicações seguras nessa porta. A porta é usada na arquitetura de comunicação cliente-servidor. A porta 443 é ativada por padrão para conexões seguras. O cliente, que pode ser qualquer cliente de automação que usa API REST, inicia a conexão com o servidor e os pontos finais trocam dados.



 a| 
8143
 a| 
As ferramentas do ONTAP escutam comunicações seguras nesta porta. A porta é usada na arquitetura de comunicação cliente-servidor. O cliente, que pode ser qualquer cliente de automação que usa API REST, inicia a conexão com o servidor e os pontos finais trocam dados. Esta porta está ativada para os serviços de ferramentas do ONTAP e para exportar logs do servidor de ferramentas do ONTAP. A página register.html está hospedada nesta porta. O Swagger RESTANTE está exposto neste porto.



 a| 
8443
 a| 
Essa porta é usada para ferramentas do ONTAP para o serviço de plug-in do VMware vSphere.



 a| 
7
 a| 
As ferramentas do ONTAP enviam uma solicitação de eco ao ONTAP para verificar a acessibilidade e são necessárias somente ao adicionar o sistema de armazenamento e podem ser desativadas posteriormente.

|===

NOTE: Você deve ter habilitado o ICMP (Internet Control Message Protocol) antes de implantar as ferramentas do ONTAP.

Se o ICMP estiver desativado, a configuração inicial das ferramentas do ONTAP falhará e as ferramentas do ONTAP não poderão iniciar as ferramentas do ONTAP para os serviços do VMware vSphere e do provedor VASA após a implantação. Você deve habilitar manualmente as ferramentas do ONTAP para os serviços do VMware vSphere e do provedor VASA após a implantação.
