---
permalink: deploy/task_deploy_ontap_tools.html 
sidebar: sidebar 
keywords:  
summary: Para usar as ferramentas do ONTAP para o dispositivo VMware vSphere, implante as ferramentas do ONTAP para VMware vSphere em seu ambiente e especifique os parâmetros necessários. 
---
= Como implantar ferramentas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para usar as ferramentas do ONTAP para o dispositivo VMware vSphere, implante as ferramentas do ONTAP para VMware vSphere em seu ambiente e especifique os parâmetros necessários.

*O que você vai precisar*

* Você deve ter a versão suportada do vCenter Server.
+

NOTE: Você pode Registrar as ferramentas do ONTAP para o VMware vSphere com uma implantação do vCenter Server ou uma implantação do VMware vCenter Server Virtual Appliance (vCSA).

+
https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade"^]

* Você deve ter configurado e configurado seu ambiente do vCenter Server.
* Você deve ter configurado um host ESXi para sua máquina virtual.
* Você deve ter baixado o arquivo _.ova_.
* Você deve ter as credenciais de login de administrador para sua instância do vCenter Server.
* Você deve ter desconetado e fechado todas as sessões do navegador do vSphere Client e excluído o cache do navegador para evitar qualquer problema de cache do navegador durante a implantação de ferramentas do ONTAP.
* Você deve ter ativado o Internet Control Message Protocol (ICMP).
+
Se o ICMP estiver desativado, a configuração inicial das ferramentas do ONTAP para VMware vSphere falhará. Você deve habilitar manualmente as ferramentas do ONTAP para os serviços do VMware vSphere e do provedor VASA após a implantação.



*Sobre esta tarefa*

O provedor VASA é habilitado por padrão para uma nova instalação de ferramentas do ONTAP para VMware vSphere. Mas no caso de uma atualização de uma versão anterior, o estado do provedor VASA é mantido e você pode precisar ativar o provedor VASA manualmente.

link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html["Habilite o provedor VASA para configurar datastores virtuais"]

*Passos*

. Faça login no vSphere Client.
. Selecione *Home* > *hosts e clusters*.
. Clique com o botão direito do rato no centro de dados pretendido e, em seguida, clique em *Deploy OVF template...*.
+

NOTE: Não implante ferramentas do ONTAP a máquina virtual VMware vSphere em um datastore vVols que ele gerencia.

. Selecione o método aplicável para fornecer o arquivo de implantação para ferramentas do ONTAP e clique em *Avançar*.
+
|===


| *Localização* | *Ação* 


 a| 
URL
 a| 
Forneça o URL para o arquivo _.ova_ para ferramentas do ONTAP.



 a| 
Pasta
 a| 
Extraia o arquivo .zip, que contém o arquivo .ova no sistema local. Na página Selecionar um modelo OVF , especifique a localização do arquivo .ova dentro da pasta extraída.

|===
. Introduza os detalhes para personalizar o assistente de implementação.
+
(Opcional) na seção Configurar vCenter ou Ativar VCF, marque a caixa de seleção *Ativar o VMware Cloud Foundation (VCF)* e forneça uma senha para as credenciais das ferramentas do ONTAP. As ferramentas do ONTAP armazenam os detalhes do usuário em um formato codificado. Para qualquer comunicação entre as ferramentas do ONTAP e o vCenter, esses detalhes de usuário do vCenter são usados. Você não precisa fornecer endereço IP, mas fornecer uma senha é obrigatório. Consulte o seguinte para obter detalhes completos.

+
** link:../deploy/reference_considerations_for_deploying_ontap_tools_for_vmware_vsphere.html["Considerações sobre personalização da implantação"]
** link:../deploy/vmware_cloud_foundation_mode_deployment.html["Modo de implantação do VMware Cloud Foundation para ferramentas do ONTAP"]


. Revise os dados de configuração e clique em *Next* para concluir a implantação.
+
À medida que espera que a implementação termine, pode ver o progresso da implementação a partir do separador tarefas.

. Ligue a máquina virtual ONTAP Tools e, em seguida, abra um console da máquina virtual que executa as ferramentas ONTAP.
. Verifique se as ferramentas do ONTAP estão em execução após a conclusão da implantação.
. Se as ferramentas do ONTAP não estiverem registradas em nenhum vCenter Server, use `\https://appliance_ip:8143/Register.html` para Registrar a instância do ONTAP Tools. O Register.html redireciona você para a página do Swagger. A partir das ferramentas do ONTAP 9,12, o Registro das ferramentas do ONTAP com o vCenter acontece na página do Swagger.
+
Use a API POST para Registrar as ferramentas do ONTAP com o vCenter a partir de 9,12.

+
[listing]
----
/2.0/plugin/vcenter
----
. Faça logout e faça login novamente no vSphere Client para visualizar as ferramentas do ONTAP implantadas.
+
Pode levar alguns minutos para que o plug-in seja atualizado no vSphere Client.

+
*Solução de problemas:* se você não conseguir visualizar o plug-in mesmo depois de fazer login, você deve limpar o cache do vSphere Client.

+
link:../deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html["Limpe os pacotes de plug-in baixados em cache do vSphere"]



link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html["Habilite o provedor VASA para configurar datastores virtuais"]

*Informações relacionadas*

https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Storage_Software%2FVirtual_Storage_Console_for_VMware_vSphere%2FError_during_fresh_deployment_of_virtual_appliance_for_VSC%252C_VASA_Provider%252C_and_SRA["Erro durante a nova implantação do dispositivo virtual para VSC, provedor VASA e SRA"]
