---
permalink: protect/configure_sra_with_srm_shared_site.html 
sidebar: sidebar 
keywords: SRA with SRM 
summary: As ferramentas do ONTAP para VMware vSphere suportam a configuração do site de recuperação compartilhada do VMware SRM. 
---
= Configure o SRA com o SRM em uma configuração de site de recuperação compartilhada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As ferramentas do ONTAP para VMware vSphere suportam a configuração do site de recuperação compartilhada SRM da VMware. Para obter mais informações, consulte:  https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-8/site-recovery-manager-installation-and-configuration-8-8.html["Site Recovery Manager em uma configuração de local de recuperação compartilhada"]. As instâncias do Site Recovery Manager Server no site de recuperação se conetam às mesmas instâncias do vCenter Server.

Em uma Configuração do local de recuperação compartilhada SRM, cada servidor SRM precisa ter uma instância SRA dedicada (relação 1:1 entre SRM e SRA). Configure o OTV no modo VCF para atuar como uma instância SRA dedicada para cada servidor SRM. Você também pode ter uma ferramenta ONTAP não habilitada para SRA para o dispositivo VMware vSphere implantada, registrada no vCenter e usada para tarefas que não sejam SRA, como provisionamento de datastore.

O https://kb.netapp.com/mgmt/OTV/SRA/Storage_Replication_Adapter%3A_How_to_configure_SRA_in_a_SRM_Shared_Recovery_Site["Como configurar o SRA em um site de recuperação compartilhada SRM"] artigo da KB detalha o procedimento para configurar o SRA para suportar a Configuração do local de recuperação partilhada SRM.
