---
permalink: protect/reference_configure_storage_replication_adapter_for_highly_scaled_environment.html 
sidebar: sidebar 
keywords:  
summary: 'Você deve configurar os intervalos de tempo de armazenamento de acordo com as configurações recomendadas para Storage Replication Adapter (SRA) para ter um desempenho ideal em ambientes altamente dimensionados.' 
---
= Configure o Storage Replication Adapter para um ambiente altamente dimensionado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar os intervalos de tempo de armazenamento de acordo com as configurações recomendadas para Storage Replication Adapter (SRA) para ter um desempenho ideal em ambientes altamente dimensionados.



== Definições do fornecedor de armazenamento

Você deve definir os seguintes valores de tempo limite no SRM para ambiente escalado:

|===


| * Configurações avançadas* | *Valores de tempo limite* 


 a| 
`StorageProvider.resignatureTimeout`
 a| 
Aumente o valor da definição de 900 segundos para 12000 segundos.



 a| 
`storageProvider.hostRescanDelaySec`
 a| 
60



 a| 
`storageProvider.hostRescanRepeatCnt`
 a| 
20



 a| 
`storageProvider.hostRescanTimeoutSec`
 a| 
Defina um valor alto (por exemplo: 99999)

|===
Você também deve ativar a `StorageProvider.autoResignatureMode` opção.

Consulte a documentação da Broadcom para obter mais informações sobre como modificar as configurações do provedor de armazenamento.

https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-8/site-recovery-manager-administration-8-8/advanced-srm-configuration/reconfigure-srm-settings/change-storage-provider-settings.html["Altere as definições do fornecedor de armazenamento"]



== Definições de armazenamento

Quando você atinge um tempo limite, aumente os valores de `storage.commandTimeout` e `storage.maxConcurrentCommandCnt` para um valor mais alto.


NOTE: O intervalo de tempo limite especificado é o valor máximo. Não é necessário esperar que o tempo limite máximo seja atingido. A maioria dos comandos termina dentro do intervalo de tempo limite máximo definido.

Você também deve definir o tempo máximo para que o SRA execute uma única operação no arquivo vvol.properties: OFFTAP.operation.timeout.period.seconds=86400.

https://kb.netapp.com/mgmt/OTV/SRA/NetApp_Storage_Replication_Adapter_4.0%2F%2F7.X_for_ONTAP_Sizing_Guide["Resposta 1001111 da base de conhecimento da NetApp: Adaptador de replicação de armazenamento NetApp 4,0/7.X para Guia de dimensionamento de ONTAP"]

A documentação da Broadcom sobre como modificar as configurações do provedor de SAN tem mais informações.

https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-8/site-recovery-manager-administration-8-8/advanced-srm-configuration/reconfigure-srm-settings/change-storage-settings.html["Altere as definições de armazenamento"]
