---
permalink: protect/task_configure_storage_replication_adapter_for_nas_environment.html 
sidebar: sidebar 
keywords:  
summary: 'Você deve configurar os sistemas de armazenamento antes de executar o Storage Replication Adapter (SRA) para o VMware vCenter Site Recovery Manager (SRM).' 
---
= Configurar o adaptador de replicação de armazenamento para ambiente nas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar os sistemas de armazenamento antes de executar o Storage Replication Adapter (SRA) para VMware vCenter Site Recovery Manager (SRM).

*O que você vai precisar*

Você deve ter instalado os seguintes programas no site protegido e no site de recuperação:

* SRM
+
A documentação sobre a instalação do SRM pode ser encontrada no site da VMware.

+
https://www.vmware.com/support/pubs/srm_pubs.html["Documentação do VMware Site Recovery Manager"]

* SRA
+
O adaptador é instalado no SRM e no servidor SRA.



*Passos*

. Verifique se os datastores no site protegido contêm máquinas virtuais registradas no vCenter Server.
. Verifique se os hosts ESXi no local protegido montaram os volumes de exportações NFS da máquina virtual de storage (SVM).
. Verifique se endereços válidos, como o endereço IP, nome do host ou FQDN em que as exportações NFS estão presentes, estão especificados no campo *endereços NFS* ao usar o assistente Array Manager para adicionar arrays ao SRM.
. Use o comando ping em cada host ESXi no local de recuperação para verificar se o host tem uma porta VMkernel que pode acessar os endereços IP usados para atender às exportações NFS do SVM.


https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"]
