---
permalink: protect/task_update_sra_credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Para que o SRM se comunique com o SRA, você deve atualizar as credenciais do SRA no servidor SRM se tiver modificado as credenciais. 
---
= Atualizar credenciais SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para que o SRM se comunique com o SRA, você deve atualizar as credenciais do SRA no servidor SRM se tiver modificado as credenciais.

Você precisa excluir a pasta da máquina SRM em cache a senha do nome de usuário do ONTAP Tools e reinstalar o SRA.

*O que você vai precisar*

Você deve ter executado as etapas mencionadas no tópico link:../protect/task_configure_sra_on_srm_appliance.html["Configurar o SRA no dispositivo SRM"]

*Passos*

. Execute os seguintes comandos para excluir a pasta da máquina SRM Cache Ferramentas ONTAP senha do nome de usuário:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd /conf`
.. `rm -rf *`


. Execute o comando perl para configurar o SRA com as novas credenciais:
+
.. `cd ..`
.. `perl command.pl -I <otv-IP> administrator <otv-password>`. Você precisa ter uma única cotação em torno do valor da senha.
+
Uma mensagem de sucesso confirmando que as credenciais de armazenamento são armazenadas é exibida. O SRA pode se comunicar com o servidor SRA usando o endereço IP, porta e credenciais fornecidos.




