---
permalink: concepts/concept_configure_high_availability_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'As ferramentas do ONTAP suportam uma configuração de alta disponibilidade (HA) para ajudar a fornecer funcionalidade ininterrupta das ferramentas do ONTAP durante a falha.' 
---
= Configurar a alta disponibilidade para ferramentas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As ferramentas do ONTAP dão suporte a uma configuração de alta disponibilidade (HA) para ajudar a fornecer funcionalidade ininterrupta das ferramentas do ONTAP durante uma falha.

As ferramentas do ONTAP dependem do recurso VMware vSphere High-Availability (HA) e do recurso vSphere Fault Tolerance (FT) para fornecer alta disponibilidade. A solução de alta disponibilidade (HA) oferece recuperação rápida de interrupções causadas por:

* Falha do host
* Falha de rede
* Falha da máquina virtual (falha do sistema operacional convidado)
* Falha na aplicação (ferramentas ONTAP)


Nenhuma configuração adicional é necessária para que as ferramentas do ONTAP forneçam alta disponibilidade. Somente os hosts do vCenter Server e do ESXi devem ser configurados com o recurso VMware vSphere HA ou o recurso vSphere FT com base em seus requisitos. Tanto a HA quanto a FT exigem hosts em cluster junto com storage compartilhado. FT tem requisitos e limitações adicionais.

Além da solução VMware vSphere HA e da solução vSphere FT, as ferramentas do ONTAP para VMware vSphere também ajudam a manter os serviços de ferramentas do ONTAP em execução o tempo todo. O processo de vigilância das ferramentas do ONTAP monitora periodicamente todos os três serviços e os reinicia automaticamente quando qualquer tipo de falha é detetada. Isso ajuda a evitar falhas de aplicativos.


NOTE: O vCenter HA não é compatível com as ferramentas do ONTAP.



== VMware vSphere HA

Você pode configurar seu ambiente vSphere no qual as ferramentas do ONTAP para VMware vSphere são implantadas para alta disponibilidade (HA). O recurso VMware HA oferece proteção contra failover contra falhas de hardware e falhas do sistema operacional em ambientes virtuais.

O recurso VMware HA monitora as máquinas virtuais para detetar falhas no sistema operacional e no hardware. Quando uma falha é detetada, o recurso VMware HA reinicia as máquinas virtuais nos outros servidores físicos no pool de recursos. A intervenção manual não é necessária quando é detetada uma falha do servidor.

O procedimento para configurar o VMware HA depende da versão do vCenter Server. Por exemplo, você pode usar o link de referência a seguir e selecionar a versão do vCenter Server necessária para exibir as etapas para configurar o VMware HA.

https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-availability/GUID-5432CA24-14F1-44E3-87FB-61D937831CF6.html["Documentação do VMware vSphere: Criando e usando clusters de HA do vSphere"]



== Tolerância de falhas do VMware vSphere

O recurso VMware vSphere Fault Tolerance (FT) oferece alta disponibilidade (HA) em um nível mais alto e permite proteger máquinas virtuais sem perda de dados ou conexões. Você deve habilitar ou desabilitar as ferramentas do vSphere FT for ONTAP a partir do seu vCenter Server.

Garanta que sua licença vSphere ofereça suporte ao FT com o número de vCPUs necessárias para as ferramentas do ONTAP em seu ambiente (pelo menos 2 vCPUs; 4 vCPUs para ambientes de grande escala).

O vSphere FT permite que as máquinas virtuais operem continuamente, mesmo durante falhas de servidor. Quando o vSphere FT está habilitado em uma máquina virtual, uma cópia da máquina virtual principal é criada automaticamente em outro host (a máquina virtual secundária) selecionado pelo DRS (Distributed Resource Scheduler). Se o DRS não estiver habilitado, o host de destino será selecionado entre os hosts disponíveis. O vSphere FT opera a máquina virtual principal e a máquina virtual secundária no modo de lockstep, com cada um espelhando o estado de execução da máquina virtual primária para a máquina virtual secundária.

Quando há uma falha de hardware que faz com que a máquina virtual primária falhe, a máquina virtual secundária imediatamente pega onde a máquina virtual principal parou. A máquina virtual secundária continua a funcionar sem perda de conexões de rede, transações ou dados.

Seu sistema deve atender aos requisitos de CPU, requisitos de limite de máquina virtual e requisitos de licenciamento para configurar o vSphere FT para sua instância do vCenter Server.

O procedimento para configurar HA depende da versão do vCenter Server. Por exemplo, você pode usar o link de referência a seguir e selecionar a versão do vCenter Server necessária para exibir as etapas para configurar o HA.

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.avail.doc/GUID-57929CF0-DA9B-407A-BF2E-E7B72708D825.html["Documentação do VMware vSphere: Requisitos, limites e licenciamento de tolerância a falhas"]
