---
permalink: concepts/concept_vcenter_server_role_based_access_control_features_in_vsc_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'O vCenter Server fornece controle de acesso baseado em função (RBAC) que permite controlar o acesso a objetos vSphere. Nas ferramentas do ONTAP para VMware vSphere, o vCenter Server RBAC trabalha com o ONTAP RBAC para determinar quais tarefas de ferramentas do ONTAP um usuário específico pode executar em objetos em um sistema de storage específico.' 
---
= Visão geral do controle de acesso baseado em funções nas ferramentas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O vCenter Server fornece controle de acesso baseado em função (RBAC) que permite controlar o acesso a objetos vSphere. O ONTAP Server RBAC trabalha com o ONTAP RBAC para determinar quais tarefas de ferramentas do ONTAP um usuário específico pode executar em objetos em um sistema de storage específico.

Para concluir uma tarefa com êxito, você precisa ter as permissões RBAC apropriadas do vCenter Server. Durante uma tarefa, as ferramentas do ONTAP verificam as permissões do vCenter Server de um usuário antes de verificar o ONTAP Privileges do usuário.

Você pode definir as permissões do vCenter Server no objeto raiz (também conhecido como a pasta raiz). Em seguida, você pode refinar a segurança restringindo entidades filhas que não precisam dessas permissões.
