---
permalink: concepts/reference_product_level_privilege_required_by_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: Para acessar as ferramentas do ONTAP para a GUI do VMware vSphere, você deve ter o privilégio de exibição específico de ferramentas do ONTAP em nível de produto atribuído no nível correto do objeto vSphere. Se você fizer login sem esse privilégio, as ferramentas do ONTAP exibem uma mensagem de erro quando você clica no ícone NetApp e impede que você acesse as ferramentas do ONTAP. 
---
= Privilégio de nível de produto exigido pelas ferramentas do ONTAP para VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para acessar as ferramentas do ONTAP para a GUI do VMware vSphere, você deve ter o privilégio de exibição específico de ferramentas do ONTAP em nível de produto atribuído no nível correto do objeto vSphere. Se você fizer login sem esse privilégio, as ferramentas do ONTAP exibem uma mensagem de erro quando você clica no ícone NetApp e impede que você acesse as ferramentas do ONTAP. No privilégio *Exibir*, você pode acessar a GUI de ferramentas do ONTAP. Este privilégio não permite que você execute tarefas dentro das ferramentas do ONTAP. Para executar qualquer tarefa de ferramentas do ONTAP, você precisa ter o vCenter Server Privileges nativo e específico de ferramentas do ONTAP correto para essas tarefas.

O nível de atribuição determina quais partes da IU você pode ver. A atribuição do privilégio Exibir no objeto raiz (pasta) permite que você entre nas ferramentas do ONTAP clicando no ícone NetApp.

Você pode atribuir o privilégio Exibir a outro nível de objeto vSphere; no entanto, isso limita os menus das ferramentas do ONTAP que você pode ver e usar.

O objeto raiz é o local recomendado para atribuir qualquer permissão que contenha o privilégio Exibir.
