---
permalink: configure/task_register_oncommand_api_services_with_ontap_tools.html 
sidebar: sidebar 
keywords: virtual volume datastores 
summary: Se você estiver usando o ONTAP 9.6 ou anterior, o painel vVols poderá exibir os detalhes dos armazenamentos de dados e máquinas virtuais do VMware Virtual volumes somente se você tiver registrado os Serviços de API do OnCommand para o provedor VASA para obter dados para os relatórios de VM e armazenamento de dados do vVols. 
---
= Registre os Serviços de API do OnCommand com as ferramentas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver usando o ONTAP 9.6 ou anterior, o painel vVols poderá exibir os detalhes dos armazenamentos de dados e máquinas virtuais do VMware Virtual volumes (vVols) somente se você tiver registrado os serviços de API do OnCommand para o provedor VASA para obter dados para os relatórios de VM e armazenamento de dados do vVols.

*O que você vai precisar*

Você deve ter baixado o OnCommand API Services 2,1 ou posterior do site de suporte da NetApp.


NOTE: O painel do vVols exibe métricas de desempenho somente quando os datastores SAN vVols e as máquinas virtuais são configurados usando o ONTAP 9.7 ou posterior.

*Passos*

. Na página inicial das ferramentas do ONTAP, clique em *Configurações*.
. Clique em *Manage Extension* (Gerenciar extensão) na guia Administrative Settings (Configurações administrativas).
. Use o controle deslizante Register OnCommand API Services para habilitar os Serviços de API do OnCommand.
. Insira o endereço IP, a porta de serviço e as credenciais dos Serviços de API da OnCommand.
+
Você também pode usar a caixa de diálogo Gerenciar extensões do provedor VASA para as seguintes modificações:

+
** Para atualizar o Registro dos Serviços de API do OnCommand quando houver alguma alteração nas credenciais.
** Para cancelar o Registro dos Serviços de API do OnCommand quando você não precisar mais do painel vVols.
+
Você deve desmarcar a caixa de seleção Registrar serviços de API do OnCommand para remover o Registro de serviços de API do OnCommand para o provedor VASA.



. Clique em *aplicar*.
+
O painel do vVols exibe as métricas para armazenamentos de dados do ONTAP 9.6 ou anteriores do SAN vVols somente após o Registro dos Serviços de API do OnCommand estar concluído.



*Informações relacionadas*

https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"]
