---
permalink: configure/task_regenerate_an_ssl_certificate_for_vsc.html 
sidebar: sidebar 
keywords:  
summary: 'O certificado SSL é gerado quando você instala as ferramentas do ONTAP. O nome distinto "(DN) que é gerado para o certificado SSL pode não ser um nome comum "(CN) que as máquinas cliente reconhecem. Ao alterar as senhas do keystore e da chave privada, você pode regenerar o certificado e criar um certificado específico do site.' 
---
= Regenerar um certificado SSL para o Virtual Storage Console
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O certificado SSL é gerado quando você instala as ferramentas do ONTAP. O nome distinto (DN) gerado para o certificado SSL pode não ser um nome comum (CN) que as máquinas cliente reconhecem. Ao alterar as senhas do keystore e da chave privada, você pode regenerar o certificado e criar um certificado específico do site.

*Sobre esta tarefa*

Você pode ativar o diagnóstico remoto usando o console de manutenção e gerar certificado específico do local.

https://kb.netapp.com/advice_and_troubleshooting/data_storage_software/vsc_and_vasa_provider/virtual_storage_console%3a_implementing_ca_signed_certificates["Console de armazenamento virtual: Implementando certificados assinados pela CA"]

*Passos*

. Inicie sessão na consola de manutenção.
. Entre `1` para aceder ao menu Application Configuration (Configuração da aplicação).
. No menu Application Configuration (Configuração da aplicação), aceda `3` para parar o serviço ONTAP Tools (Ferramentas do sistema).
. Digite `7` para regenerar o certificado SSL.

