---
permalink: configure/task_enable_datastore_mounting_across_different_subnets.html 
sidebar: sidebar 
keywords:  
summary: Se você usar iSCSI ou NFS e a sub-rede for diferente entre os hosts ESXi e o sistema de storage, será necessário modificar as ferramentas do ONTAP para os arquivos de preferências do VMware vSphere. Se você não modificar o arquivo de preferências, o provisionamento do datastore falhará porque as ferramentas do ONTAP não podem montar o datastore. 
---
= Habilite a montagem do datastore em diferentes sub-redes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você usar iSCSI ou NFS e a sub-rede for diferente entre os hosts ESXi e o sistema de storage, será necessário modificar as ferramentas do ONTAP para os arquivos de preferências do VMware vSphere. Se você não modificar o arquivo de preferências, o provisionamento do datastore falhará porque as ferramentas do ONTAP não podem montar o datastore.

*Sobre esta tarefa*

Quando o provisionamento do armazenamento de dados falha, as ferramentas do ONTAP para VMware vSphere Registram as seguintes mensagens de erro:

'Não foi possível continuar. Não foram encontrados endereços ip quando se faz referência cruzada a endereços ip do kernel e endereços no controlador. Não foi possível encontrar uma rede correspondente ao volume de montagem NFS para esses hosts.'

*Passos*

. Faça login na instância do vCenter Server.
. Inicie o console de manutenção usando sua máquina virtual unificada de dispositivos.
+
link:../manage/reference_maintenance_console_of_ontap_tools_for_vmware_vsphere.html["Console de manutenção das ferramentas do ONTAP para VMware vSphere"]

. Entre `4` para acessar a opção suporte e Diagnóstico.
. Digite `2` para acessar a opção Access Diagnostic Shell (Concha de Diagnóstico de Acesso).
. Introduza `vi /opt/netapp/vscserver/etc/kamino/kaminoprefs.xml` para atualizar o `kaminoprefs.xml` ficheiro.
. Atualize o `kaminoprefs.xml` ficheiro.
+
|===


| *Se você usar...* | *Faça isso...* 


 a| 
ISCSI
 a| 
Altere o valor da chave de entrada `default.allow.iscsi.mount.networks` DE TODOS para o valor das redes de host ESXi.



 a| 
NFS
 a| 
Altere o valor da chave de entrada `default.allow.nfs.mount.networks` DE TODOS para o valor das redes de host ESXi.

|===
+
O arquivo de preferências inclui valores de amostra para essas chaves de entrada.

+

NOTE: O valor "TUDO" não significa todas as redes. O valor "'ALL'" permite que todas as redes correspondentes, entre o host e o sistema de armazenamento, sejam usadas para a montagem de datastores. Quando você especifica redes de host, você pode habilitar a montagem somente nas sub-redes especificadas.

. Salve e feche o `kaminoprefs.xml` arquivo.

