---
permalink: configure/task_refresh_the_storage_system_display.html 
sidebar: sidebar 
keywords:  
summary: Você pode usar o recurso de atualização fornecido pelas ferramentas do ONTAP para o VMware vSphere para atualizar as informações sobre sistemas de armazenamento e forçar as ferramentas do ONTAP a descobrir sistemas de armazenamento. 
---
= Atualize a apresentação do sistema de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o recurso de atualização fornecido pelas ferramentas do ONTAP para o VMware vSphere para atualizar as informações sobre sistemas de armazenamento e forçar as ferramentas do ONTAP a descobrir sistemas de armazenamento.

*Sobre esta tarefa*

A `refresh` opção é útil se você alterou as credenciais padrão para os sistemas de armazenamento após receber um erro de autenticação. Você sempre deve executar uma operação de atualização se você tiver alterado as credenciais do sistema de storage depois que o sistema de storage informou um `Authentication Failure Status`. durante a operação de atualização, as ferramentas do ONTAP tentam se conetar ao sistema de storage usando as novas credenciais.

Dependendo da configuração do sistema, essa tarefa pode levar muito tempo para ser concluída.

*Passos*

. Na página inicial do VMware vSphere Client, clique em *Storage*.
. Inicie a atualização:
+
|===


| *Se esta localização é...* | *Clique...* 


 a| 
Console de armazenamento virtual
 a| 
O ícone *REDESCOBRIR TUDO*.



 a| 
Data center
 a| 
Clique com o botão direito do rato no centro de dados e, em seguida, clique em *Ferramentas do NetApp ONTAP* > *Atualizar dados de anfitrião e armazenamento*.

|===
. Na caixa de diálogo Atualizar dados do host e do armazenamento, clique em *OK*.
+
A descoberta pode levar alguns minutos, dependendo do número de hosts e sistemas de storage em seu data center. Esta operação de descoberta funciona em segundo plano.

. Clique em *OK* na caixa de diálogo sucesso.

