---
permalink: manage/reference_verify_vvols_dashboard_data_requirements.html 
sidebar: sidebar 
keywords: vVol dashboard 
summary: Você deve verificar alguns requisitos importantes do painel do vVols para exibir detalhes dinâmicos dos datastores e máquinas virtuais do VMware Virtual volumes. 
---
= Requisitos de dados do painel do vVols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve verificar alguns requisitos importantes do painel do vVols para exibir detalhes dinâmicos dos datastores e máquinas virtuais do VMware Virtual volumes (vVols).

A tabela a seguir apresenta uma visão geral do que você deve verificar se o painel vVols não exibe as métricas de desempenho dos datastores SAN vVols provisionados e das máquinas virtuais.

|===
| *Considerações* | *Descrição* 


 a| 
Sistema de storage
 a| 
* Você está usando o ONTAP 9.7 ou posterior.
* Você está usando as credenciais apropriadas para o sistema de storage.
* Seu sistema de storage está ativo e acessível.
* A máquina virtual selecionada deve estar usando pelo menos um datastore vVols e as operações de e/S estão sendo executadas no disco da máquina virtual.


|===