---
permalink: manage/task_edit_esxi_host_settings.html 
sidebar: sidebar 
keywords:  
summary: Você pode usar o painel das ferramentas do ONTAP para o VMware vSphere para editar as configurações do host ESXi. 
---
= Modifique as configurações do host ESXi usando as ferramentas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o painel das ferramentas do ONTAP para o VMware vSphere para editar as configurações do host ESXi.

*O que você vai precisar*

Você deve ter configurado um sistema host ESXi para sua instância do vCenter Server.

Se houver um problema com as configurações do host ESXi, o problema será exibido no portlet ESXi Host Systems do painel. Você pode clicar no problema para exibir o nome do host ou o endereço IP do host ESXi que tem o problema.

*Passos*

. Na página inicial do vSphere Client, clique em *Ferramentas do ONTAP*.
. Edite as configurações do host ESXi.
+
|===


| *Se você quiser editar as configurações do host ESXi de...* | *Faça isso...* 


 a| 
Problemas exibidos
 a| 
.. Clique no problema no portlet ESXi Host Systems.
.. Clique nos nomes de host ESXi para os quais você deseja modificar as configurações.
.. Clique com o botão direito no nome do host ESXi e clique em *Ferramentas NetApp ONTAP* > *Definir valores recomendados*.
.. Modifique as configurações necessárias e clique em *OK*.




 a| 
Página inicial do vSphere Client
 a| 
.. Clique em *Menu* > *hosts e clusters*.
.. Clique com o botão direito do rato no anfitrião ESXi pretendido e selecione *Ferramentas NetApp ONTAP* > *Definir valor recomendado*.
.. Clique em *OK*.




 a| 
Portlet ESXi host Systems
 a| 
.. Clique na guia *painel tradicional* na seção Visão geral das ferramentas do ONTAP.
.. Clique em *Editar configurações do host ESXi*.
.. Selecione o nome do host ESXi na guia Configurações e status do host para o qual você deseja modificar as configurações e clique em *PRÓXIMO*.
.. Selecione as configurações necessárias na guia Configurações recomendadas do host e clique em *Avançar*.
.. Revise sua seleção na guia Resumo e clique em *FINISH*.


|===

