---
permalink: manage/task_monitor_datastores_using_the_traditional_dashboard.html 
sidebar: sidebar 
keywords:  
summary: Você pode monitorar os armazenamentos de dados tradicionais e as máquinas virtuais usando o painel tradicional das ferramentas do ONTAP. Os dados do dashboard permitem analisar o uso do armazenamento de dados e tomar medidas corretivas para evitar que as máquinas virtuais sejam executadas em restrições relacionadas ao espaço. 
---
= Analise dados de desempenho usando o painel tradicional
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode monitorar os armazenamentos de dados tradicionais e as máquinas virtuais usando o painel tradicional das ferramentas do ONTAP. Os dados do dashboard permitem analisar o uso do armazenamento de dados e tomar medidas corretivas para evitar que as máquinas virtuais sejam executadas em restrições relacionadas ao espaço.

*O que você vai precisar*

Você deve selecionar a opção *Ativar controle de e/S de armazenamento e coleta de estatísticas* ou *Desativar controle de e/S de armazenamento, mas habilitar coleção de estatísticas* na caixa de diálogo Configurar controle de e/S de armazenamento. Você pode ativar o Controle de e/S de storage somente se tiver a licença Enterprise Plus da VMware.

https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/6-5/vsphere-resource-management-6-5.html["Gerenciamento de recursos do vSphere"]

O painel tradicional exibe as métricas de IOPS, espaço utilizado, latência e capacidade comprometida obtidas do vCenter Server. O ONTAP fornece métricas agregadas de economia de espaço ao painel tradicional. Você pode exibir economia de espaço para um agregado específico. Esses parâmetros de desempenho permitem identificar gargalos de desempenho no ambiente virtual e tomar medidas corretivas para resolver os problemas.


NOTE: O monitoramento de arquivos não é compatível com datastores FlexGroup configurados em máquinas virtuais de armazenamento direto (SVMs).

O dashboard tradicional das ferramentas do ONTAP permite visualizar armazenamentos de dados NFS ou armazenamentos de dados VMFS. Você pode clicar em um datastore para navegar até a visualização de detalhes do datastore fornecida pela instância do vCenter Server para exibir e corrigir quaisquer problemas com os datastores no vCenter Server.

*Passos*

. Na página inicial do vSphere Client, clique em *Ferramentas do ONTAP para VMware vSphere*.
. Selecione o vCenter Server necessário usando o seletor *INSTANCE* para exibir os datastores.
. Clique em *Visão geral > Painel tradicional*.
+
O portlet de datastores fornece os seguintes detalhes:

+
** O número de armazenamentos de dados tradicionais, juntamente com suas métricas de desempenho gerenciadas por ferramentas do ONTAP na instância do vCenter Server
** Os cinco principais armazenamentos de dados com base nos parâmetros de desempenho e uso de recursos que podem ser modificados, se necessário, você pode alterar a listagem dos armazenamentos de dados com base no espaço utilizado, IOPS ou latência e na ordem necessária.


+
O portlet máquinas virtuais fornece os seguintes detalhes:

+
** Número de máquinas virtuais que usam datastores NetApp no vCenter Server
** As cinco principais máquinas virtuais baseadas na capacidade comprometida, latência, IOPS, taxa de transferência e tempo de atividade
+
Os dados de IOPS e taxa de transferência no portlet máquinas virtuais estão disponíveis apenas para datastores criados em volumes com backup do FlexGroup.




