---
permalink: manage/task_migrate_virtual_machines_with_older_storage_capability_profiles.html 
sidebar: sidebar 
keywords:  
summary: 'Se você estiver usando a versão mais recente das ferramentas do ONTAP para VMware vSphere, então você deve migrar suas máquinas virtuais que são provisionadas com as métricas de QoS "MAXTHROUGHPUT MBPS" ou "MaxThroughput IOPS" para novos armazenamentos de dados VVol que são provisionados com as métricas de QoS "IOPS máximo" da versão mais recente das ferramentas do ONTAP.' 
---
= Migrar máquinas virtuais com perfis de capacidade de storage mais antigos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver usando a versão mais recente das ferramentas do ONTAP para o VMware vSphere, então você deve migrar suas máquinas virtuais que são provisionadas com as métricas de QoS "'MAXTHROUGHPUT MBPS'" ou "'MaxThroughput IOPS'" para novos armazenamentos de dados VVol que são provisionados com as métricas de QoS "'IOPS máximo'" da versão mais recente das ferramentas do ONTAP.

*Sobre esta tarefa*

Com a versão mais recente das ferramentas do ONTAP, você pode configurar métricas de QoS para cada máquina virtual ou disco de máquina virtual (VMDK). As métricas de QoS foram aplicadas anteriormente no nível ONTAP FlexVol volume e foram compartilhadas por todas as máquinas virtuais ou VMDKs provisionadas nesse FlexVol volume.

A partir da versão 7,2 das ferramentas do ONTAP, as métricas de QoS de uma máquina virtual não são compartilhadas com outras máquinas virtuais.


NOTE: Você não deve modificar a Política de armazenamento de VM existente, pois as máquinas virtuais podem se tornar não compatíveis.

*Passos*

. Crie armazenamentos de dados vVols usando um novo perfil de capacidade de armazenamento com o valor "'Max IOPS'" necessário.
. Crie uma Política de armazenamento de VM e mapeie a nova Política de armazenamento de VM com o novo perfil de capacidade de armazenamento.
. Migre as máquinas virtuais existentes para os armazenamentos de dados VVol recém-criados usando a nova Política de armazenamento de VM.

